/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  ContractTransaction,
  Overrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import type { FunctionFragment, Result } from "@ethersproject/abi";
import type { Listener, Provider } from "@ethersproject/providers";
import type {
  TypedEventFilter,
  TypedEvent,
  TypedListener,
  OnEvent,
  PromiseOrValue,
} from "./common";

export type OrderInfoStruct = {
  reactor: PromiseOrValue<string>;
  swapper: PromiseOrValue<string>;
  nonce: PromiseOrValue<BigNumberish>;
  deadline: PromiseOrValue<BigNumberish>;
  preExecutionHook: PromiseOrValue<string>;
  preExecutionHookData: PromiseOrValue<BytesLike>;
  postExecutionHook: PromiseOrValue<string>;
  postExecutionHookData: PromiseOrValue<BytesLike>;
  auctionResolver: PromiseOrValue<string>;
};

export type OrderInfoStructOutput = [
  string,
  string,
  BigNumber,
  BigNumber,
  string,
  string,
  string,
  string,
  string
] & {
  reactor: string;
  swapper: string;
  nonce: BigNumber;
  deadline: BigNumber;
  preExecutionHook: string;
  preExecutionHookData: string;
  postExecutionHook: string;
  postExecutionHookData: string;
  auctionResolver: string;
};

export type InputTokenStruct = {
  token: PromiseOrValue<string>;
  amount: PromiseOrValue<BigNumberish>;
  maxAmount: PromiseOrValue<BigNumberish>;
};

export type InputTokenStructOutput = [string, BigNumber, BigNumber] & {
  token: string;
  amount: BigNumber;
  maxAmount: BigNumber;
};

export type OutputTokenStruct = {
  token: PromiseOrValue<string>;
  amount: PromiseOrValue<BigNumberish>;
  recipient: PromiseOrValue<string>;
};

export type OutputTokenStructOutput = [string, BigNumber, string] & {
  token: string;
  amount: BigNumber;
  recipient: string;
};

export type ResolvedOrderStruct = {
  info: OrderInfoStruct;
  input: InputTokenStruct;
  outputs: OutputTokenStruct[];
  sig: PromiseOrValue<BytesLike>;
  hash: PromiseOrValue<BytesLike>;
  auctionResolver: PromiseOrValue<string>;
  witnessTypeString: PromiseOrValue<string>;
};

export type ResolvedOrderStructOutput = [
  OrderInfoStructOutput,
  InputTokenStructOutput,
  OutputTokenStructOutput[],
  string,
  string,
  string,
  string
] & {
  info: OrderInfoStructOutput;
  input: InputTokenStructOutput;
  outputs: OutputTokenStructOutput[];
  sig: string;
  hash: string;
  auctionResolver: string;
  witnessTypeString: string;
};

export interface TokenTransferHookInterface extends utils.Interface {
  functions: {
    "permit2()": FunctionFragment;
    "preExecutionHook(address,((address,address,uint256,uint256,address,bytes,address,bytes,address),(address,uint256,uint256),(address,uint256,address)[],bytes,bytes32,address,string))": FunctionFragment;
    "reactor()": FunctionFragment;
  };

  getFunction(
    nameOrSignatureOrTopic: "permit2" | "preExecutionHook" | "reactor"
  ): FunctionFragment;

  encodeFunctionData(functionFragment: "permit2", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "preExecutionHook",
    values: [PromiseOrValue<string>, ResolvedOrderStruct]
  ): string;
  encodeFunctionData(functionFragment: "reactor", values?: undefined): string;

  decodeFunctionResult(functionFragment: "permit2", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "preExecutionHook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "reactor", data: BytesLike): Result;

  events: {};
}

export interface TokenTransferHook extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TokenTransferHookInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    permit2(overrides?: CallOverrides): Promise<[string]>;

    preExecutionHook(
      filler: PromiseOrValue<string>,
      resolvedOrder: ResolvedOrderStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>;

    reactor(overrides?: CallOverrides): Promise<[string]>;
  };

  permit2(overrides?: CallOverrides): Promise<string>;

  preExecutionHook(
    filler: PromiseOrValue<string>,
    resolvedOrder: ResolvedOrderStruct,
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ContractTransaction>;

  reactor(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    permit2(overrides?: CallOverrides): Promise<string>;

    preExecutionHook(
      filler: PromiseOrValue<string>,
      resolvedOrder: ResolvedOrderStruct,
      overrides?: CallOverrides
    ): Promise<void>;

    reactor(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    permit2(overrides?: CallOverrides): Promise<BigNumber>;

    preExecutionHook(
      filler: PromiseOrValue<string>,
      resolvedOrder: ResolvedOrderStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<BigNumber>;

    reactor(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    permit2(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    preExecutionHook(
      filler: PromiseOrValue<string>,
      resolvedOrder: ResolvedOrderStruct,
      overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<PopulatedTransaction>;

    reactor(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
