/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { PermitPost } from './PermitPost';
export * as factories from './factories';
export { PermitPost__factory } from './factories/PermitPost__factory';
