/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type {
  ExclusiveFillerValidation,
  ExclusiveFillerValidationInterface,
} from "../ExclusiveFillerValidation";

const _abi = [
  {
    inputs: [],
    name: "NotExclusiveFiller",
    type: "error",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "filler",
        type: "address",
      },
      {
        components: [
          {
            components: [
              {
                internalType: "contract IReactor",
                name: "reactor",
                type: "address",
              },
              {
                internalType: "address",
                name: "swapper",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "nonce",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "deadline",
                type: "uint256",
              },
              {
                internalType: "contract IValidationCallback",
                name: "validationContract",
                type: "address",
              },
              {
                internalType: "bytes",
                name: "validationData",
                type: "bytes",
              },
            ],
            internalType: "struct OrderInfo",
            name: "info",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "contract ERC20",
                name: "token",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
              {
                internalType: "uint256",
                name: "maxAmount",
                type: "uint256",
              },
            ],
            internalType: "struct InputToken",
            name: "input",
            type: "tuple",
          },
          {
            components: [
              {
                internalType: "address",
                name: "token",
                type: "address",
              },
              {
                internalType: "uint256",
                name: "amount",
                type: "uint256",
              },
              {
                internalType: "address",
                name: "recipient",
                type: "address",
              },
            ],
            internalType: "struct OutputToken[]",
            name: "outputs",
            type: "tuple[]",
          },
          {
            internalType: "bytes",
            name: "sig",
            type: "bytes",
          },
          {
            internalType: "bytes32",
            name: "hash",
            type: "bytes32",
          },
        ],
        internalType: "struct ResolvedOrder",
        name: "resolvedOrder",
        type: "tuple",
      },
    ],
    name: "validate",
    outputs: [],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610272806100206000396000f3fe608060405234801561001057600080fd5b506004361061002b5760003560e01c80636e84ba2b14610030575b600080fd5b61004361003e36600461010f565b610045565b005b6000806100528380610166565b6100609060a08101906101a4565b81019061006d9190610210565b915091504281101580156100ad57508173ffffffffffffffffffffffffffffffffffffffff168473ffffffffffffffffffffffffffffffffffffffff1614155b156100e4576040517f062dec5600000000000000000000000000000000000000000000000000000000815260040160405180910390fd5b50505050565b73ffffffffffffffffffffffffffffffffffffffff8116811461010c57600080fd5b50565b6000806040838503121561012257600080fd5b823561012d816100ea565b9150602083013567ffffffffffffffff81111561014957600080fd5b830160e0818603121561015b57600080fd5b809150509250929050565b600082357fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff4183360301811261019a57600080fd5b9190910192915050565b60008083357fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffe18436030181126101d957600080fd5b83018035915067ffffffffffffffff8211156101f457600080fd5b60200191503681900382131561020957600080fd5b9250929050565b6000806040838503121561022357600080fd5b823561022e816100ea565b94602093909301359350505056fea2646970667358221220343f716608e500b1f3bc31159441a878683e7e642c2c8960bffc1bf28c292b1d64736f6c63430008130033";

type ExclusiveFillerValidationConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ExclusiveFillerValidationConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ExclusiveFillerValidation__factory extends ContractFactory {
  constructor(...args: ExclusiveFillerValidationConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<ExclusiveFillerValidation> {
    return super.deploy(overrides || {}) as Promise<ExclusiveFillerValidation>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): ExclusiveFillerValidation {
    return super.attach(address) as ExclusiveFillerValidation;
  }
  override connect(signer: Signer): ExclusiveFillerValidation__factory {
    return super.connect(signer) as ExclusiveFillerValidation__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ExclusiveFillerValidationInterface {
    return new utils.Interface(_abi) as ExclusiveFillerValidationInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): ExclusiveFillerValidation {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as ExclusiveFillerValidation;
  }
}
