name: "Push changes to beta and alpha branches"

on:
  push:
    branches:
      - main

jobs:
  dev-branch-push:
    name: "Push to beta and alpha branches"
    environment:
      name: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@7884fcad6b5d53d10323aee724dc68d8b9096a2e
        with:
          token: ${{ secrets.SERVICE_ACCOUNT_PAT }}
          ref: main

      - name: Setup git
        run: |
          git config user.name "UL Mobile Service Account"
          git config user.email "hello-happy-puppy@users.noreply.github.com"

      - name: ↗️  Push to beta
        run: |
          git push -u origin main:beta --force
